public class JFrameFinal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFinal
     */
    public JFrameFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbox_Intel = new javax.swing.JComboBox<>();
        cbox_AMD = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbox_Memory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbox_Hard = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbox_Optical = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbox_Graphics = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rbtnWinDefault = new javax.swing.JRadioButton();
        rbtnWinPro = new javax.swing.JRadioButton();
        rbtnLinux = new javax.swing.JRadioButton();
        cboxHomeStudent = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cboxHomeBusiness = new javax.swing.JCheckBox();
        cboxAccounting = new javax.swing.JCheckBox();
        cboxGraphics = new javax.swing.JCheckBox();
        jbtn_Calculate = new javax.swing.JButton();
        tfieldCalculateAnswer = new javax.swing.JTextField();
        tfieldTax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Intel System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("AMD System");

        cbox_Intel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Processor", "G1620 2.70GHz", "G1630 2.80GHz", "G1820 2.70GHx", "G1830 2.80GHz" }));

        cbox_AMD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Processor", "FX-8350", "FX-9590", "FX-4100", "FX-4300" }));
        cbox_AMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_AMDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Memory");

        cbox_Memory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select RAM", "6 GB", "8 GB", "12 GB", "16 GB" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hard Drive");

        cbox_Hard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hard Drive", "250 GB", "500 GB", "1 TB" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Optical Drive");

        cbox_Optical.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Optical Drive", "DVD Drive", "Combo DVD/CDRW", "DVD and CDRW" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Graphics ");

        cbox_Graphics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Graphics", "NVIDA GeForce G310 512MB DDR3", "NVIDA GeForce GT620 1GB DDR3", "NVIDA GeForce GT640 1GB GDDR5" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Operating System");

        buttonGroup1.add(rbtnWinDefault);
        rbtnWinDefault.setText("Windows 8.1 Default");

        buttonGroup1.add(rbtnWinPro);
        rbtnWinPro.setText("Windows 8.1 Pro");

        buttonGroup1.add(rbtnLinux);
        rbtnLinux.setText("Linux");

        cboxHomeStudent.setText("Microsoft Office Home & Student 2013");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("App Packages");

        cboxHomeBusiness.setText("Microsoft Office Home & Business 2013");

        cboxAccounting.setText("Accounting Package");

        cboxGraphics.setText("Graphics Package");

        jbtn_Calculate.setText("Calculate");
        jbtn_Calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_CalculateMouseClicked(evt);
            }
        });

        tfieldCalculateAnswer.setText("$Total Cost");

        tfieldTax.setText("$Total Tax");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tax");

        btnExit.setText("EXIT");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(rbtnWinDefault)
                                .addComponent(rbtnLinux)
                                .addComponent(jbtn_Calculate)
                                .addComponent(rbtnWinPro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxAccounting)
                                    .addComponent(cboxHomeBusiness)
                                    .addComponent(cboxHomeStudent)
                                    .addComponent(jLabel8)
                                    .addComponent(cboxGraphics)
                                    .addComponent(cbox_Graphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbox_Hard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbox_AMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(tfieldCalculateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbox_Optical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbox_Intel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbox_Memory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_Intel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_AMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_Memory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_Hard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_Optical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_Graphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnWinDefault)
                    .addComponent(cboxHomeStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnWinPro)
                    .addComponent(cboxHomeBusiness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnLinux)
                    .addComponent(cboxAccounting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxGraphics)
                    .addComponent(jbtn_Calculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldCalculateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        int total=0;
        if(cbox_Intel.getSelectedIndex()==1)
        {
            total+=50;
        }
        if(cbox_Intel.getSelectedIndex()==2)
        {
            total+=90;
        }
        if(cbox_Intel.getSelectedIndex()==3)
        {
            total+=105;
        }
        if(cbox_Intel.getSelectedIndex()==4)
        {
            total+=130;
        }
        if(cbox_AMD.getSelectedIndex()==1)
        {
            total+=25;
        }
        if(cbox_AMD.getSelectedIndex()==2)
        {
            total+=90;
        }
        if(cbox_AMD.getSelectedIndex()==3)
        {
            total+=187;
        }
        if(cbox_AMD.getSelectedIndex()==4)
        {
            total+=280;
        }
        if(cbox_Memory.getSelectedIndex()==1)
        {
            total+=28;
        }
        if(cbox_Memory.getSelectedIndex()==2)
        {
            total+=58;
        }
        if(cbox_Memory.getSelectedIndex()==3)
        {
            total+=108;
        }
        if(cbox_Memory.getSelectedIndex()==4)
        {
            total+=176;
        }
        if(cbox_Hard.getSelectedIndex()==1)
        {
            total+=27;
        }
        if(cbox_Hard.getSelectedIndex()==2)
        {
            total+=50;
        }
        if(cbox_Hard.getSelectedIndex()==3)
        {
            total+=89;
        }
        if(cbox_Optical.getSelectedIndex()==1)
        {
            total+=17;
        }
        if(cbox_Optical.getSelectedIndex()==2)
        {
            total+=40;
        }
        if(cbox_Optical.getSelectedIndex()==3)
        {
            total+=79;
        }
        if(cbox_Graphics.getSelectedIndex()==1)
        {
            total+=80;
        }
        if(cbox_Graphics.getSelectedIndex()==2)
        {
            total+=169;
        }
        if(cbox_Graphics.getSelectedIndex()==3)
        {
            total+=490;
        }
        if(rbtnWinDefault.isSelected())
        {
        }
        if (rbtnWinPro.isSelected())
        {
            total+=59;
        }
        if (rbtnLinux.isSelected())
        {
            total=-89;
        }
        if (cboxHomeStudent.isSelected())
        {
            total+=139;
        }
        if (cboxHomeBusiness.isSelected())
        {
            total+=219;
        }
        if (cboxAccounting.isSelected())
        {
            total+=399;
        }
        if (cboxGraphics.isSelected())
        {
            total+=499;
        }
        tfieldCalculateAnswer.setText(Integer.toString(total));

        pack();
    }// </editor-fold>                        

    private void jbtn_CalculateMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:

        
        final double SALESTAX = 0.078;
double total = 0;
double tax;
double SHIPPINGHANDLING = 0.025;
double shipping = total * SHIPPINGHANDLING;
if(cbox_Intel.getSelectedIndex()==1)
    {
        total+=50;
    }
    if(cbox_Intel.getSelectedIndex()==2)
    {
        total+=90;
    }        
    if(cbox_Intel.getSelectedIndex()==3)
    {
        total+=105;
    }
    if(cbox_Intel.getSelectedIndex()==4)
    {
        total+=130;
    }
    if(cbox_AMD.getSelectedIndex()==1)
    {
        total+=25;
    }
    if(cbox_AMD.getSelectedIndex()==2)
    {
        total+=90;
    }
    if(cbox_AMD.getSelectedIndex()==3)
    {
        total+=187;
    }
    if(cbox_AMD.getSelectedIndex()==4)
    {
        total+=280;
    }
    if(cbox_Memory.getSelectedIndex()==1)
    {
        total+=28;
    }
    if(cbox_Memory.getSelectedIndex()==2)
    {
        total+=58;
    }
    if(cbox_Memory.getSelectedIndex()==3)
    {
        total+=108;
    }
    if(cbox_Memory.getSelectedIndex()==4)
    {
        total+=176;
    }
    if(cbox_Hard.getSelectedIndex()==1)
    {
        total+=27;
    }
    if(cbox_Hard.getSelectedIndex()==2)
    {
        total+=50;
    }
    if(cbox_Hard.getSelectedIndex()==3)
    {
        total+=89;
    }
    if(cbox_Optical.getSelectedIndex()==1)
    {
        total+=17;
    }
    if(cbox_Optical.getSelectedIndex()==2)
    {
        total+=40;
    }
    if(cbox_Optical.getSelectedIndex()==3)
    {
        total+=79;
    }
    if(cbox_Graphics.getSelectedIndex()==1)
    {
        total+=80;
    }
    if(cbox_Graphics.getSelectedIndex()==2)
    {
        total+=169;
    }
    if(cbox_Graphics.getSelectedIndex()==3)
    {
        total+=490;
    }
    if(rbtnWinDefault.isSelected())
    {
    }
    if (rbtnWinPro.isSelected())
    {
        total+=59;
    }
    if (rbtnLinux.isSelected())
    {
        total=-89;
    }
    if (cboxHomeStudent.isSelected())
    {
        total+=139;
    }
    if (cboxHomeBusiness.isSelected())
    {
        total+=219;
    }
    if (cboxAccounting.isSelected())
    {
        total+=399;
    }
    if (cboxGraphics.isSelected())
    {
        total+=499;
    }
 tfieldCalculateAnswer.setText(Integer.toString((int) total));
total = Double.parseDouble(tfieldCalculateAnswer.getText());
tax = total * SALESTAX;
         
total = total + tax + shipping;

tfieldTax.setText(Double.toString(tax));
tfieldCalculateAnswer.setText(Double.toString(total));

    }                                           

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        System.exit(0);
    }                                    

    private void cbox_AMDActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameFinal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cboxAccounting;
    private javax.swing.JCheckBox cboxGraphics;
    private javax.swing.JCheckBox cboxHomeBusiness;
    private javax.swing.JCheckBox cboxHomeStudent;
    private javax.swing.JComboBox<String> cbox_AMD;
    private javax.swing.JComboBox<String> cbox_Graphics;
    private javax.swing.JComboBox<String> cbox_Hard;
    private javax.swing.JComboBox<String> cbox_Intel;
    private javax.swing.JComboBox<String> cbox_Memory;
    private javax.swing.JComboBox<String> cbox_Optical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtn_Calculate;
    private javax.swing.JRadioButton rbtnLinux;
    private javax.swing.JRadioButton rbtnWinDefault;
    private javax.swing.JRadioButton rbtnWinPro;
    private javax.swing.JTextField tfieldCalculateAnswer;
    private javax.swing.JTextField tfieldTax;
    // End of variables declaration                   
}
